version: '3'
services:
  app:
    container_name: ecs-app
    ports:
      - "9000:9000" ## php-fpmはデフォルトで9000番ポート
      - "5173:5173" ## viteを利用するためのポート
    build:
      context: .
      dockerfile: .docker/php/Dockerfile # docker/php/Dockerfileのなかの内容でimageを作成
    volumes:
      - ./:/app  # カレントディレクトリの内容をphpのimageの中にマウント(コピー)
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
        - mysql

  nginx:
    container_name: ecs-nginx
    ports:
      - "80:80" ## ホスト名だけでアクセスできるようにしたいので、httpの80ポート、host側を変える場合は他の変更箇所なし
    build: ## コンテナ側のportを変えるときは、default.confのlistenの変更必要、ホスト側が変更するとlocalhost:portでアクセス可能
      context: .
      dockerfile: .docker/nginx/Dockerfile  #dockerfile内でimageをbuild
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    container_name: ecs-mysql
    ports:
        - "3306:3306"
    build:
        context: .
        dockerfile: .docker/mysql/Dockerfile # docker/mysql/Dockerfileのなかの内容でimageを作成
    environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: password #rootユーザーのパスワード
        MYSQL_USER: user #userのユーザー名
        MYSQL_PASSWORD: password #userのパスワード
    volumes:
        - .docker/mysql/db/:/var/lib/mysql/ #永続化させるために記述、mysqlサーバ側fileなどをホストにマウントさせる
        - .docker/mysql/my.cnf:/etc/mysql/conf.d/my.conf #mysqlの設定を記述

  minio:
      image: minio/minio
      container_name: ecs-minio
      ports:
          - "9001:9001"
          - "9002:9002"
      environment:
          MINIO_ROOT_USER: access_key
          MINIO_ROOT_PASSWORD: secret_key
      entrypoint: bash
      command: -c "/usr/bin/minio server /export --address :9001 --console-address :9002"
