version: '3'
services:
  app:
    container_name: ecs-app
    ports:
      - "9000:9000" ## php-fpmはデフォルトで9000番ポート
    build:
      context: .
      dockerfile: .docker/php/Dockerfile # docker/php/Dockerfileのなかの内容でimageを作成
    volumes:
      - ./:/app  # カレントディレクトリの内容をphpのimageの中にマウント(コピー)
      - .docker/php/php.ini:/usr/local/etc/php/php.ini

