version: '3'
services:
  app:
    container_name: ecs-app
    ports:
      - "${FASTCGI_PORT:-9000}:9000"
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/app
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
