name: deploy

on:
  push:
    branches:
      - main
      - feat/push_images_to_ecr  # TODO 動作検証後削除

jobs:
  deploy:
    name: Deploy app to AWS Fargate
    runs-on: ubuntu-latest

    steps:
      - name: Configure aws credentials for prod
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }›
          aws-region: ${{ env.AWS_REGION }}
